<a href="https://colab.research.google.com/github/Pesaru-Sathyendra-Varma/DATA-MINING/blob/main/DM_LAB_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Transformation**

In [1]:
import pandas as pd

In [2]:
col_data = {'Color': ['Red','Green','Blue','Yellow','Black','White']}
df_col = pd.DataFrame(col_data)
df_col

    Color
0     Red
1   Green
2    Blue
3  Yellow
4   Black
5   White

**Perform One Hot Encoding**

In [3]:
one_hot_encoded = pd.get_dummies(df_col['Color'],prefix='Color')

In [4]:
one_hot_encoded = one_hot_encoded.astype(int)

In [5]:
one_hot_encoded

   Color_Black  Color_Blue  Color_Green  Color_Red  Color_White  Color_Yellow
0            0           0            0          1            0             0
1            0           0            1          0            0             0
2            0           1            0          0            0             0
3            0           0            0          0            0             1
4            1           0            0          0            0             0
5            0           0            0          0            1             0

**Label Encoding**

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
label_encoder = LabelEncoder()

In [8]:
df_col['Color_Label'] = label_encoder.fit_transform(df_col['Color'])

In [9]:
df_col['Color_Label']

0    3
1    2
2    1
3    5
4    0
5    4
Name: Color_Label, dtype: int64

In [10]:
df_col['Color']

0       Red
1     Green
2      Blue
3    Yellow
4     Black
5     White
Name: Color, dtype: object

#**One-Hot-Encoding of Titanic.csv**

In [13]:
df=pd.read_csv('/content/titanic.csv')

In [14]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
one_hot_encoded_titanic= pd.get_dummies(df['Sex'],prefix='Sex')

In [16]:
one_hot_encoded_titanic= one_hot_encoded_titanic.astype(int)

In [17]:
one_hot_encoded_titanic

     Sex_female  Sex_male
0             0         1
1             1         0
2             1         0
3             1         0
4             0         1
..          ...       ...
886           0         1
887           1         0
888           1         0
889           0         1
890           0         1

[891 rows x 2 columns]

#**Label Encoding of Titanic.csv**

In [18]:
df['Gender']=df['Sex'].map({'male':1,'female':0})

In [19]:
le= LabelEncoder()

In [20]:
df['Gender'] = le.fit_transform(df['Sex'])

In [21]:
df['Gender']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Gender, Length: 891, dtype: int64

#**Employee Salary**

In [26]:
emp = pd.read_csv('/content/EMP_SAL.csv')

In [24]:
emp

NameError: name 'emp' is not defined

In [27]:
emp['Salary']=emp['BASIC_PAY']+emp['HRA']+emp['DA']-emp['TAX']

In [28]:
emp['Salary']

0      88200
1      93300
2      98400
3     103500
4     108600
5     113700
6     118800
7     123900
8     129000
9     134100
10    139200
11    144300
12    149400
13    154500
Name: Salary, dtype: int64

In [38]:
from datetime import datetime

In [39]:
emp['DOB'] = pd.to_datetime(emp['DOB'],format='%d-%m-%Y')

In [45]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DOB        14 non-null     datetime64[ns]
 1   BASIC_PAY  14 non-null     int64
 2   HRA        14 non-null     int64
 3   DA         14 non-null     int64
 4   TAX        14 non-null     int64
 5   Salary     14 non-null     int64
dtypes: datetime64[ns](1), int64(5)
memory usage: 804.0 bytes

In [46]:
today = pd.Timestamp('now')

In [47]:
today

Timestamp('2025-02-05 04:03:25.341920')

In [49]:
emp['age'] = today.year - emp['DOB'].dt.year - ((today.month < emp['DOB'].dt.month) | ((today.month == emp['DOB'].dt.month) & (today.day < emp['DOB'].dt.day))).astype(int)

In [50]:
emp['age']

0     20
1     22
2     24
3     26
4     28
5     30
6     32
7     34
8     36
9     38
10    40
11    42
12    44
13    46
Name: age, dtype: int64